### Profile ###

include="~~/profiles.conf"

### Video ###

vo=gpu-next
vd-lavc-dr=yes
hwdec-codecs=all
gpu-context=winvk
gpu-shader-cache=yes
vulkan-async-compute=no
vulkan-async-transfer=yes
vulkan-swap-mode=fifo
vulkan-device=NVIDIA GeForce RTX 4050
icc-profile-auto=yes
icc-intent=2
icc-3dlut-size=64x64x64
icc-cache-dir="~~/icc-cache"
hwdec=nvdec

dither-depth=auto
temporal-dither=yes
dither=error-diffusion
error-diffusion=atkinson

interpolation=yes
framedrop=no
tscale=oversample
interpolation-preserve=yes
tscale-blur=1
tscale-clamp=0.0
tscale-radius=1.0
tscale-taper=0.0
tscale-antiring=0.01
video-sync-max-video-change=0.01
video-sync=display-resample (Enable for high hz display)
tscale-blur=0.6991556596428412

deband=no

### Audio and Subtitles ###

slang=en,eng,English,en-US,US
alang=ja,jp,jpn,jap,Japanese,en,eng,English

# SUBTITLES
sub-font="Segoe UI Light"
sub-font-size=40
sub-color="#FFFFFF"
sub-border-size=1.0
sub-outline-color="#FFFFFF"
sub-shadow-color="#000000"
sub-shadow-offset=0.5
sub-blur=0.0
sub-back-color="#00000000"
sub-auto=fuzzy
sub-ass-override=yes
sub-ass-scale-with-window=no
sub-fix-timing=yes
blend-subtitles=yes
demuxer-mkv-subtitle-preroll=yes
sub-file-paths=sub,subs,subtitles
slang=en,eng,English
alang=en,eng,English
script-opts-append=trackselect-preferred_sub_lang=en/eng/english
script-opts-append=trackselect-preferred_sub_words=hearing_impaired/SDH/HI
script-opts-append=trackselect-excluded_sub_words=sign/s&s
script-opts-append=trackselect-preferred_audio_lang=en/eng/English
sub-clear-on-seek=yes
sub-delay=0

# AUDIO
ao=wasapi
audio-exclusive=no
audio-device=auto
audio-normalize-downmix=yes
audio-channels=auto
gapless-audio=yes
audio-pitch-correction=yes
audio-file-auto=fuzzy
audio-buffer=0.1
demuxer-readahead-secs=10
demuxer-max-bytes=200M
volume=100
audio-channels=7.1,5.1,stereo          

### Functions ###
osc=no
osd-bar=no
osd-bold=yes
border=no
autofit=60%x60%
ontop=no
snap-window=yes
cursor-autohide=600
force-window=yes
idle=yes

# PLAYBACK BEHAVIOR
keep-open=no
keep-open-pause=no
force-seekable=yes
save-position-on-quit=yes
directory-mode=ignore

# Enable cache
cache=yes
cache-on-disk=yes
cache-dir="C:\mpv-cache"
cache-max-file-size=10G
demuxer-max-bytes=10000M
demuxer-max-back-bytes=5000M
stream-buffer-size=8M

# YTDL FORMAT FILTER
ytdl-format=bestvideo[height<=?2160][vcodec~=av01]+bestaudio[format_id!*=-drc]/bestvideo[height<=?2160][vcodec*=vp9]+bestaudio[format_id!*=-drc]/bestvideo[height<=?2160]+bestaudio[format_id!*=-drc]/best
hls-bitrate=max

# SEEKING
hr-seek=yes
hr-seek-framedrop=no

# OSD FLASH STYLING
osd-font="Segoe UI"
osd-font-size=26
osd-color="#FFFFFF"
osd-border-color="#000000"
osd-border-size=1
osd-shadow-color="#000000"
osd-shadow-offset=1
osd-align-x=center
osd-align-y=top
osd-margin-y=40
osd-level=1
osd-status-msg=${filename}
osd-duration=3000


